version: "3.7"

# Based on https://github.com/nicolargo/docker-influxdb-grafana
# https://github.com/Coac/fluentd-influxdb-grafana
services:
  # Documentation environment  https://hub.docker.com/_/influxdb           
  influxdb:
    image: arm32v7/influxdb:latest
    container_name: influxdb
    healthcheck:
      test: "curl -f http://localhost:8086/ping"
      interval: 3s
      timeout: 10s
      retries: 5
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
    env_file:
      - 'env.influxdb'
    volumes:
      # Data persistency
      # sudo mkdir -p /srv/docker/influxdb/data
      - ./srv/docker/influxdb/data:/var/lib/influxdb
      - ./influxdb.conf:/etc/influxdb/influxdb.conf:ro
    restart: always
    
  chronograf:
    image: chronograf:latest
    ports:
      - '8888:8888'
    volumes:
      - chronograf-storage:/var/lib/chronograf
      - /proc/sysrq-trigger:/sysrq
    depends_on:
      - influxdb
    env_file:
      - 'env.chronograf'
    restart: always

  telegraf:
    image: arm32v7/telegraf:latest
    hostname: 'localhost'
    container_name: telegraf
    env_file:
      - 'env.telegraf'
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /:/hostfs:ro
      - /etc:/hostfs/etc:ro
      - /proc:/hostfs/proc:ro
      - /sys:/hostfs/sys:ro
      - /var:/hostfs/var:ro
      - /run:/hostfs/run:ro
    depends_on:
      - influxdb
    restart: always

  # https://brjapon.medium.com/monitoring-raspberry-pi-4-performance-in-real-time-fd598d46c273
  # https://stackoverflow.com/a/24759427
  kapacitor:
    image: arm32v7/kapacitor
    container_name: kapacitor
    env_file: env.kapacitor
    volumes:
      - ./kapacitor.conf:/etc/kapacitor/kapacitor.conf:ro
      # Mount for kapacitor data directory
      - kapacitor-storage:/var/lib/kapacitor
      # https://github.com/influxdata/kapacitor/tree/master/examples/load
      - ./kapacitor:/etc/kapacitor/load/
      # Expose dbus to shutdown
      - /proc/sysrq-trigger:/sysrq
    depends_on:
      - influxdb
    links:
      - influxdb
    ports:
      # The API for Kapacitor is served on port 9092
      - "9092:9092"
    healthcheck:
      test: "curl http://localhost:9092/kapacitor/v1/ping"
      interval: 10s
      timeout: 10s
      retries: 10
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    env_file:
      - 'env.grafana'
    user: "0"
    volumes:
      # Data persistency
      # sudo mkdir -p /srv/docker/grafana/data; chown 472:472 /srv/docker/grafana/data
      - ./srv/docker/grafana/data:/var/lib/grafana
      - ./srv/docker/grafana/provisioning/:/etc/grafana/provisioning/
    depends_on:
      - influxdb
    restart: always

  weather: 
    build: weather
    env_file: weather/.env
    restart: unless-stopped
    depends_on:
      - influxdb

  solarman-mqtt:
    build: solarman
    env_file: solarman/.env
    restart: unless-stopped
    expose:
    - 1883
    ports:
    - "1883:1883"
    depends_on:
      - influxdb
    restart: always

volumes:
  influxdb-storage:
  chronograf-storage:
  grafana-storage:
  kapacitor-storage:
